//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public int Clients_Id { get; set; }
        public int Pitch_Id { get; set; }
        public int Rooms_Id { get; set; }
        public System.DateTime Reservation_Date { get; set; }
        public int Price { get; set; }
        public System.DateTime Reservation_Deadline { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pitch Pitch { get; set; }
        public virtual Room Room { get; set; }
    }
}
