//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskClient()
        {
            this.Comment_Report = new HashSet<Comment_Report>();
        }
    
        public int Id { get; set; }
        public string TaskName { get; set; }
        public System.DateTime Task_Date { get; set; }
        public System.DateTime Deadline { get; set; }
        public int Client_Id { get; set; }
        public byte Status { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Report> Comment_Report { get; set; }
    }
}
